{ types, mkOption }: let
definitions = {"#/definitions/CacheConfig" = {"capacity" = mkOption { type = types.int;};
"time_to_idle" = mkOption { type = types.int;};
"time_to_live" = mkOption { type = types.int;};
};
"#/definitions/ClientBootstrapModuleInfo" = {"chain_id" = mkOption { type = types.str;};
"client_type" = mkOption { type = types.str;};
};
"#/definitions/ClientModuleInfo" = {"client_type" = mkOption { type = types.str;};
"consensus_type" = mkOption { type = types.str;};
"ibc_interface" = mkOption { type = types.str;};
"ibc_spec_id" = mkOption { type = types.str;};
};
"#/definitions/Config" = {"state" = mkOption { type = definitions."#/definitions/CacheConfig";};
};
"#/definitions/Duration" = {"nanos" = mkOption { type = types.int;};
"secs" = mkOption { type = types.int;};
};
"#/definitions/FinalityModuleInfo" = {"chain_id" = mkOption { type = types.str;};
"consensus_type" = mkOption { type = types.str;};
};
"#/definitions/ModuleConfig_for_ClientBootstrapModuleInfo" = {"config" = mkOption { type = types.attrs;};
"enabled" = mkOption { type = types.bool;};
"info" = mkOption { type = definitions."#/definitions/ClientBootstrapModuleInfo";};
"path" = mkOption { type = types.str;};
};
"#/definitions/ModuleConfig_for_ClientModuleInfo" = {"config" = mkOption { type = types.attrs;};
"enabled" = mkOption { type = types.bool;};
"info" = mkOption { type = definitions."#/definitions/ClientModuleInfo";};
"path" = mkOption { type = types.str;};
};
"#/definitions/ModuleConfig_for_FinalityModuleInfo" = {"config" = mkOption { type = types.attrs;};
"enabled" = mkOption { type = types.bool;};
"info" = mkOption { type = definitions."#/definitions/FinalityModuleInfo";};
"path" = mkOption { type = types.str;};
};
"#/definitions/ModuleConfig_for_ProofModuleInfo" = {"config" = mkOption { type = types.attrs;};
"enabled" = mkOption { type = types.bool;};
"info" = mkOption { type = definitions."#/definitions/ProofModuleInfo";};
"path" = mkOption { type = types.str;};
};
"#/definitions/ModuleConfig_for_StateModuleInfo" = {"config" = mkOption { type = types.attrs;};
"enabled" = mkOption { type = types.bool;};
"info" = mkOption { type = definitions."#/definitions/StateModuleInfo";};
"path" = mkOption { type = types.str;};
};
"#/definitions/ModulesConfig" = {"client" = mkOption { type = types.listOf (definitions."#/definitions/ModuleConfig_for_ClientModuleInfo");};
"client_bootstrap" = mkOption { type = types.listOf (definitions."#/definitions/ModuleConfig_for_ClientBootstrapModuleInfo");};
"consensus" = mkOption { type = types.listOf (definitions."#/definitions/ModuleConfig_for_FinalityModuleInfo");};
"proof" = mkOption { type = types.listOf (definitions."#/definitions/ModuleConfig_for_ProofModuleInfo");};
"state" = mkOption { type = types.listOf (definitions."#/definitions/ModuleConfig_for_StateModuleInfo");};
};
"#/definitions/PluginConfig" = {"config" = mkOption { type = types.any;};
"enabled" = mkOption { type = types.bool;};
"path" = mkOption { type = types.str;};
};
"#/definitions/ProofModuleInfo" = {"chain_id" = mkOption { type = types.str;};
"ibc_spec_id" = mkOption { type = types.str;};
};
"#/definitions/QueueConfig" = types.attrs;
"#/definitions/StateModuleInfo" = {"chain_id" = mkOption { type = types.str;};
"ibc_spec_id" = mkOption { type = types.str;};
};
"#/definitions/VoyagerConfig" = {"cache" = mkOption { type = definitions."#/definitions/Config";};
"ipc_client_request_timeout" = mkOption { type = definitions."#/definitions/Duration";};
"metrics_endpoint" = mkOption { type = types.str;};
"num_workers" = mkOption { type = types.int;};
"optimizer_delay_milliseconds" = mkOption { type = types.int;};
"queue" = mkOption { type = definitions."#/definitions/QueueConfig";};
"rest_laddr" = mkOption { type = types.str;};
"rpc_laddr" = mkOption { type = types.str;};
};
};
in
types.submodule { options = {"$schema" = mkOption { type = types.str;};
"equivalent_chain_ids" = mkOption { type = types.listOf (types.listOf (types.str));};
"modules" = mkOption { type = definitions."#/definitions/ModulesConfig";};
"plugins" = mkOption { type = types.listOf (definitions."#/definitions/PluginConfig");};
"voyager" = mkOption { type = definitions."#/definitions/VoyagerConfig";};
};}
